# Based on igbinary's appveyor config.
# This tests against the latest stable minor version of PHP 7 (Currently 7.1)
# Author: Tyson Andre

version: '{branch}.{build}'

install:
- cmd: choco feature enable -n=allowGlobalConfirmation
- cmd: mkdir %APPVEYOR_BUILD_FOLDER%\bin

branches:
  only:
    - master

build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat"

    appveyor DownloadFile http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip

    7z x -y php-sdk-binary-tools-20110915.zip -oC:\projects\php-sdk

    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    git clone --depth=1 --branch=PHP-7.1 https://github.com/php/php-src C:\projects\php-src

    mkdir C:\projects\php-src\ext\runkit

    xcopy %APPVEYOR_BUILD_FOLDER% C:\projects\php-src\ext\runkit /s /e /y

    appveyor DownloadFile http://windows.php.net/downloads/php-sdk/deps-7.1-vc14-x86.7z

    7z x -y deps-7.1-vc14-x86.7z -oC:\projects\php-src

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --disable-all --enable-session --enable-debug --enable-cli --enable-cgi --enable-runkit --enable-runkit-spl_object_id --enable-json --with-config-file-scan-dir=%APPVEYOR_BUILD_FOLDER%\bin\modules.d --with-prefix=%APPVEYOR_BUILD_FOLDER%\bin --with-php-build=deps

    nmake


test_script:
- cmd: cd C:\projects\php-src
- cmd: set NO_INTERACTION=1
- cmd: set REPORT_EXIT_STATUS=1
- cmd: nmake test TESTS="C:\projects\php-src\ext\runkit\tests --show-diff"

# Would require `nmake install` in the build script.
#artifacts:
#  - path: bin
#    name: master
#    type: zip
